package com.openclassrooms.magicgithub.api

import com.openclassrooms.magicgithub.model.User

class FakeApiService : ApiService {
    private val _users = FakeApiServiceGenerator.FAKE_USERS

    /**
     * Return a list of [User]
     * Those users must be generated by [FakeApiServiceGenerator]
     */
    override fun getUsers(): List<User> {
        return _users
    }

    /**
     * Generate a random [User] and add it [FakeApiService.users] list.
     * This user must be get from the [FakeApiServiceGenerator.FAKE_USERS_RANDOM] list.
     */
    override fun addRandomUser() {
        _users.add(FakeApiServiceGenerator.FAKE_USERS_RANDOM.random())
    }

    /**
     * Delete a [User] from the [FakeApiService.users] list.
     */
    override fun deleteUser(user: User) {
        _users.remove(user)
    }

    /**
     * Set a [User] active or inactive.
     */
    override fun setActiveInactive(user: User) {
        val newUser = user.copy(isActive = !user.isActive)
        val position = _users.indexOf(user)
        _users[position] = newUser
    }

    /**
     * Swap two [User] in the [FakeApiService.users] list.
     */
    override fun swapUsers(from: Int, to: Int) {
        val userFrom = _users[from]
        _users[from] = _users[to]
        _users[to] = userFrom
    }
}